<script>
     const add=(num1, num2)=>{
        return new Promise((resolve, reject)=>{
            setTimeout(()=>{
                console.log('Timeout')
                if(num1<0 || num2<0){
                    // fail
                    return reject('Negative Number Error')
                }
                // success
                resolve(num1+num2)
            },2000)

        })
     }
     //const addPromise=add(10,20)
     //console.log(addPromise)

     add(10,20)
        .then((sum)=>{
            // success
            console.log('sum : '+sum)
            return add(sum, 30)     // return promise
        })
        .then((sum)=>{
            console.log('Sum : '+sum)            
            return add(sum, 40)
        })
        .then((sum)=>{
            console.log('Sum : '+sum)            
        })
        .catch((err)=>{
            // fail
            console.log(err)
        })
    console.log('Exit')
</script>